// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAvmrpaffPk8FT0XVVuWrb-qrE-Qfc3mV8',
    appId: '1:305530821720:android:236b9ac55aa57aed047e2d',
    messagingSenderId: '305530821720',
    projectId: 'bit-news-6fef6',
    storageBucket: 'bit-news-6fef6.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAgZlMIygW08hGqSVZpQ4_ijxTinNNrvi4',
    appId: '1:305530821720:ios:868be0d1baf16e1b047e2d',
    messagingSenderId: '305530821720',
    projectId: 'bit-news-6fef6',
    storageBucket: 'bit-news-6fef6.appspot.com',
    androidClientId: '305530821720-3n2c2a964prgeaklfv43ragokt3fp314.apps.googleusercontent.com',
    iosClientId: '305530821720-9s2so50dvkeua7f21su753u3o6ol9oqm.apps.googleusercontent.com',
    iosBundleId: 'com.example.bitnews',
  );
}
